version: '3.7'

services:
  db:
    container_name: postgresql-bentley-container
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    restart: unless-stopped
    networks:
      - web_network
      - db_network
    logging:
      driver: none

  pgadmin4:
    container_name: pgadminn4-bentley-container
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    networks:
      - db_network
    restart: unless-stopped
    logging:
      driver: none

  web:
    container_name: fastapi-bentley-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
#    command: >
#      sh -c "uvicorn main:app --reload --host --app-dir bentley_ottmann_api 0.0.0.0 --port 8000"
    networks:
      - web_network
      - db_network
    restart: on-failure

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  pgadmin:
  postgres_data: